//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBNCover.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.imgURLSoap")]
    public interface imgURLSoap {
        
        // CODEGEN: Generating message contract since element name isbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnImgURL", ReplyAction="*")]
        ISBNCover.ServiceReference1.ReturnImgURLResponse ReturnImgURL(ISBNCover.ServiceReference1.ReturnImgURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnImgURL", ReplyAction="*")]
        System.Threading.Tasks.Task<ISBNCover.ServiceReference1.ReturnImgURLResponse> ReturnImgURLAsync(ISBNCover.ServiceReference1.ReturnImgURLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnImgURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnImgURL", Namespace="http://tempuri.org/", Order=0)]
        public ISBNCover.ServiceReference1.ReturnImgURLRequestBody Body;
        
        public ReturnImgURLRequest() {
        }
        
        public ReturnImgURLRequest(ISBNCover.ServiceReference1.ReturnImgURLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnImgURLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        public ReturnImgURLRequestBody() {
        }
        
        public ReturnImgURLRequestBody(string isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnImgURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnImgURLResponse", Namespace="http://tempuri.org/", Order=0)]
        public ISBNCover.ServiceReference1.ReturnImgURLResponseBody Body;
        
        public ReturnImgURLResponse() {
        }
        
        public ReturnImgURLResponse(ISBNCover.ServiceReference1.ReturnImgURLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnImgURLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReturnImgURLResult;
        
        public ReturnImgURLResponseBody() {
        }
        
        public ReturnImgURLResponseBody(string ReturnImgURLResult) {
            this.ReturnImgURLResult = ReturnImgURLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface imgURLSoapChannel : ISBNCover.ServiceReference1.imgURLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class imgURLSoapClient : System.ServiceModel.ClientBase<ISBNCover.ServiceReference1.imgURLSoap>, ISBNCover.ServiceReference1.imgURLSoap {
        
        public imgURLSoapClient() {
        }
        
        public imgURLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public imgURLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public imgURLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public imgURLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISBNCover.ServiceReference1.ReturnImgURLResponse ISBNCover.ServiceReference1.imgURLSoap.ReturnImgURL(ISBNCover.ServiceReference1.ReturnImgURLRequest request) {
            return base.Channel.ReturnImgURL(request);
        }
        
        public string ReturnImgURL(string isbn) {
            ISBNCover.ServiceReference1.ReturnImgURLRequest inValue = new ISBNCover.ServiceReference1.ReturnImgURLRequest();
            inValue.Body = new ISBNCover.ServiceReference1.ReturnImgURLRequestBody();
            inValue.Body.isbn = isbn;
            ISBNCover.ServiceReference1.ReturnImgURLResponse retVal = ((ISBNCover.ServiceReference1.imgURLSoap)(this)).ReturnImgURL(inValue);
            return retVal.Body.ReturnImgURLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISBNCover.ServiceReference1.ReturnImgURLResponse> ISBNCover.ServiceReference1.imgURLSoap.ReturnImgURLAsync(ISBNCover.ServiceReference1.ReturnImgURLRequest request) {
            return base.Channel.ReturnImgURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISBNCover.ServiceReference1.ReturnImgURLResponse> ReturnImgURLAsync(string isbn) {
            ISBNCover.ServiceReference1.ReturnImgURLRequest inValue = new ISBNCover.ServiceReference1.ReturnImgURLRequest();
            inValue.Body = new ISBNCover.ServiceReference1.ReturnImgURLRequestBody();
            inValue.Body.isbn = isbn;
            return ((ISBNCover.ServiceReference1.imgURLSoap)(this)).ReturnImgURLAsync(inValue);
        }
    }
}
